# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

repos:
- repo: https://github.com/AFPy/powrap
  rev: v1.0.1
  hooks:
  - id: powrap