# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

repos:
- repo: local
  hooks:
    - id: format-with-powrap
      name: format-with-powrap
      entry: ./pre-commit.sh
      language: system